baseURL = 'https://docs.flags.gg'
languageCode = 'en-us'
title = 'Flags.gg Documentation'

[module]

[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'
disable = false
ignoreConfig = false

[params]
description = 'Flags.gg Documentation'
author = 'Flags.gg'
showVisitedLinks = true
linkTitle = 'Flags.gg'

[outputs]
home = ['HTML', 'RSS', 'JSON']
section = ['HTML', 'RSS', 'JSON']
page = ['HTML', 'RSS', 'JSON']
