version: "3"
vars:
  SERVICE_NAME: docs
  NAMESPACE: flags-gg
tasks:
  make-temp-files:
    cmds:
      - task: get-latest-tag
  get-latest-tag:
    cmds:
      - |
        git fetch --tags
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        if [[ -z "$latest_tag" ]]; then
          echo "0.0.1" > .latest_tag
        else
          echo $latest_tag | awk -F. '{printf "%d.%d.%d", $1, $2, $3}' > .latest_tag
        fi
    silent: true
  clean-git-file:
    cmds:
      - rm .latest_tag

  # Deploy Commands
  deploy-latest-tag:
    cmds:
      - kubectl set image deployment/{{.SERVICE_NAME}} {{.SERVICE_NAME}}=containers.chewed-k8s.net/{{.NAMESPACE}}/{{.SERVICE_NAME}}:{{.LATEST_TAG}} -n {{.NAMESPACE}}
      - kubectl rollout restart deployment/{{.SERVICE_NAME}} -n {{.NAMESPACE}}
    vars:
      LATEST_TAG:
        sh: cat .latest_tag
