# Builder
FROM node:22-alpine AS builder
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

# Runner
FROM caddy:2-alpine AS runner

COPY --from=builder /app/dist /srv
COPY ./Caddyfile /etc/caddy/Caddyfile

EXPOSE 80
EXPOSE 443
